### PR TITLE
(Fix) - Sort orderbook by price

### LINKED ISSUE #41: Sort orderbook by price
SRA Docs:

> Bids will be sorted in descending order by price, and asks will be sorted in ascending order by price. Within the price sorted orders, the orders are further sorted by taker fee price which is defined as the takerFee divided by takerTokenAmount. After taker fee price, orders are to be sorted by expiration in ascending order.

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #41 

Implements the sorting of bids/asks for the `GET /v2/orderbook` endpoint as stated in the SRA v2:
https://github.com/0xProject/standard-relayer-api/blob/master/http/v2.md#get-v2orderbook

- Sort bids in descending order by price: `makerAssetAmount/takerAssetAmount`.
- Sort asks in ascending order by price: `takerAssetAmount/makerAssetAmount`.
- The orders are further sorted by taker fee price. After taker fee price, orders are to be sorted by expiration in ascending order.

### CODE REVIEW

File: ts/src/orderbook.ts [hunk 1]
```diff
@@ -269,6 +271,36 @@ export class OrderBook {
...
+    const orderAPrice = orderA.makerAssetAmount.div(orderA.takerAssetAmount);
+    const orderBPrice = orderB.makerAssetAmount.div(orderB.takerAssetAmount);
+    if (!orderAPrice.isEqualTo(orderBPrice)) {
+        return orderBPrice.comparedTo(orderAPrice);
+    }
+
+    return compareOrder(orderA, orderB);
+};
+
+const compareOrder = (orderA: SignedOrder, orderB: SignedOrder): number => {
```
Comment (fabioberger) [inline ts/src/orderbook.ts]: Let's rename this to `compareOrderByFeeRatio` as it better describes what this method is doing.

**Review by fabioberger — CHANGES_REQUESTED** [review]
Thanks for the PR! Could you also please minor bump the package's version in `package.json` and add an entry in `CHANGELOG.md`?

**Review by LogvinovLeon — APPROVED** [review]

File: ts/src/orderbook.ts (hunk 1 above)
Comment (mariano-aguero) [reply ts/src/orderbook.ts]: > Let's rename this to `compareOrderByFeeRatio` as it better describes what this method is doing.

Thanks for the feedback! Done here https://github.com/0xProject/0x-launch-kit/pull/56/commits/7e55f27e0b969967cb0e9b9d67b81e0a313a8a51 . 

Regards

**Comment by mariano-aguero** [comment]
> Thanks for the PR! Could you also please minor bump the package's version in `package.json` and add an entry in `CHANGELOG.md`?

Thanks for the feedback! The version was updated (`yarn version --minor`) and also added an entry in the `CHANGELOG.md`. 

Regards

**Review by fabioberger — APPROVED** [review]
